#!/usr/bin/env bash
set -euo pipefail
# Render this host's hardware and access identity to stdout. Versioned
# topology and service configuration are deliberately absent.

for v in INTERFACE_MAC ADMIN_KEYS; do
  [ -n "${!v:-}" ] || { printf 'render-machine-values: %s is not set\n' "$v" >&2; exit 1; }
done

json_string() {
  local s=$1
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  printf '"%s"' "$s"
}

json_list() {
  local indent=$1 first=1 item
  while IFS= read -r item; do
    [ -n "$item" ] || continue
    [ "$first" -eq 1 ] || printf ',\n'
    printf '%s%s' "$indent" "$(json_string "$item")"
    first=0
  done <<<"$2"
  [ "$first" -eq 1 ] || printf '\n'
}

cat <<EOF
{
  "_comment": "Machine facts generated by bootstrap-collector. Stored at /var/lib/ahara-collector/machine-values.json and overlaid by the updater.",
  "interfaceMac": $(json_string "$INTERFACE_MAC"),
  "adminAuthorizedKeys": [
$(json_list "    " "$ADMIN_KEYS")  ]
}
EOF
